### PR TITLE
Fixed gradient ID collision.

### PR DESCRIPTION
**Pull request by sebimoe**
When placing multiple funnels on one page, all of them share the same colors, defined on the first funnel.  This change adds a unique identifier to the definition name, making funnel colours independent.

Added an example file demonstrating the issue at examples/example-multiple.html

### CODE REVIEW

**Comment by sebimoe** [comment]
Also I forgot to mention, I have made it possible to pass a HTML DOM element instance as the "container" configuration parameter. Before, it required a string selector and in my use case I had to programatically attach an attribute to the container element to "generate" a selector. I hope you don't mind having it in one PR.

**Comment by sebimoe** [comment]
I added recompiled dist files - please let me know if you would like me to create a separate pull request with just 1 commit or perhaps it's possible to squash them?

**Comment by greghub** [comment]
@sebimoe thank you very much for the great work! This was really helpful

**Comment by amarsyla** [comment]
@sebimoe @greghub I think there is a bug when passing an HTMLDom element as the container. Instead of checking for `this.container instanceOf HTMLElement` it should be `this.containerSelector instanceOf HTMLElement`. I'm submitting a pull request with this fix.

**Pull request merged**
